/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.Concessionaria;
import Classes.Funcionario;
import Classes.Locatario;
import Classes.TipoLocatario;
import Classes.UF;
import Database.Persistencia;
import Excecoes.UFInvalidaException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Vitor
 */
public class TelaCadastroCliente extends javax.swing.JDialog {

    /**
     * Creates new form TelaCadastroCliente
     */
    private Locatario locatarioEdicao;
    public TelaCadastroCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public TelaCadastroCliente(java.awt.Frame parent, boolean modal, Locatario locatario) {
        super(parent, modal);
        initComponents();
        this.locatarioEdicao = locatario;
        this.jbRemover.setEnabled(true);
       
        
    }
    private boolean logarFuncionarioAoCadastrar;

    public boolean isLogarFuncionarioAoCadastrar() {
        return logarFuncionarioAoCadastrar;
    }

    public void setLogarFuncionarioAoCadastrar(boolean logarFuncionarioAoCadastrar) {
        this.logarFuncionarioAoCadastrar = logarFuncionarioAoCadastrar;
    }
    public void carregarDadosLocatarioEdicao(){
       if(locatarioEdicao.getClass().equals(Locatario.class)){
           carregarDadosLocatario();
       }
       else if(locatarioEdicao.getClass().equals(Funcionario.class)){
           carregarDadosFuncionario();
       }
       else if(locatarioEdicao.getClass().equals(Concessionaria.class)){
           carregarDadosConcessionaria();
       }
       
       this.rbConcessionaria.setEnabled(false);
       this.rbFuncionario.setEnabled(false);
       this.rbPFisica.setEnabled(false);
       this.rbPJuridica.setEnabled(false);
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        tfCidade = new javax.swing.JTextField();
        rbPJuridica = new javax.swing.JRadioButton();
        tfUF = new javax.swing.JTextField();
        rbFuncionario = new javax.swing.JRadioButton();
        tfNumero = new javax.swing.JTextField();
        rbPFisica = new javax.swing.JRadioButton();
        tfRua = new javax.swing.JTextField();
        tfNome = new javax.swing.JTextField();
        tfBairro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfDiaNascimento = new javax.swing.JSpinner();
        tfMesNascimento = new javax.swing.JSpinner();
        tfAnoNascimento = new javax.swing.JSpinner();
        tfRazaoSocial = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfCPF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfCNPJ = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfIE = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tfCEP = new javax.swing.JTextField();
        rbConcessionaria = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tfTelefonePrincipal = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tfTelefone2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tfEmailPrincipal = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tfEmail2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        tfNIS = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tfSalario = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jpDiaAdmissao = new javax.swing.JSpinner();
        jpMesAdmissao = new javax.swing.JSpinner();
        jpAnoAdmissao = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        tfNomeResponsavel = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jbCadastar = new javax.swing.JButton();
        jbRemover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buttonGroup1.add(rbPJuridica);
        rbPJuridica.setText("Pessoa Jurídica");

        buttonGroup1.add(rbFuncionario);
        rbFuncionario.setText("Funcionário");

        buttonGroup1.add(rbPFisica);
        rbPFisica.setSelected(true);
        rbPFisica.setText("Pessoa Física");

        jLabel10.setText("Data de Nascimento/Fundação:");

        tfDiaNascimento.setValue(1);
        tfDiaNascimento.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tfDiaNascimentoStateChanged(evt);
            }
        });

        tfMesNascimento.setValue(1);
        tfMesNascimento.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tfMesNascimentojpDiaAdmissaoStateChanged(evt);
            }
        });

        tfAnoNascimento.setValue(1990);
        tfAnoNascimento.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tfAnoNascimentojpDiaAdmissaoStateChanged(evt);
            }
        });

        jLabel9.setText("Razão Social:");

        jLabel1.setText("Nome/Fantasia:");

        jLabel2.setText("Rua:");

        jLabel11.setText("CPF:");

        jLabel3.setText("Nº:");

        jLabel4.setText("Cep:");

        jLabel12.setText("CNPJ:");

        jLabel5.setText("Bairro:");

        jLabel6.setText("Cidade:");

        jLabel13.setText("I.E.:");

        jLabel7.setText("UF:");

        jLabel14.setText("Tipo de Cadastro:");

        buttonGroup1.add(rbConcessionaria);
        rbConcessionaria.setText("Concessionária");

        jLabel22.setText("Id:");

        tfId.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfDiaNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfMesNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAnoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfCidade, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfBairro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfRua, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbPJuridica)
                                    .addComponent(rbFuncionario))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbConcessionaria)
                                    .addComponent(rbPFisica))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfUF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tfIE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                        .addComponent(tfCNPJ, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfCPF, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tfCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tfIE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfDiaNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMesNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAnoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tfUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(rbPJuridica)
                    .addComponent(rbPFisica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbFuncionario)
                    .addComponent(rbConcessionaria))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Dados Genéricos", jPanel1);

        jLabel8.setText("Telefone Principal:");

        jLabel18.setText("Telefone 2:");

        tfTelefone2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTelefone2ActionPerformed(evt);
            }
        });

        jLabel19.setText("Email Principal:");

        jLabel20.setText("Email 2:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTelefone2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTelefonePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfEmailPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfEmail2)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfTelefonePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tfTelefone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tfEmailPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addContainerGap(218, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dados de Contato", jPanel3);

        jLabel15.setText("NIS:");

        jLabel16.setText("Data de Admissão:");

        jLabel17.setText("Salário:");

        jpDiaAdmissao.setValue(1);
        jpDiaAdmissao.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jpDiaAdmissaoStateChanged(evt);
            }
        });

        jpMesAdmissao.setValue(1);
        jpMesAdmissao.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jpMesAdmissaojpDiaAdmissaoStateChanged(evt);
            }
        });

        jpAnoAdmissao.setValue(1990);
        jpAnoAdmissao.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jpAnoAdmissaojpDiaAdmissaoStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfNIS, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpDiaAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpMesAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpAnoAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(264, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jpDiaAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpMesAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpAnoAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addContainerGap(271, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dados Funcionais", jPanel2);

        jLabel21.setText("Nome do Reponsável:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNomeResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tfNomeResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(323, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dados de Concessionária", jPanel4);

        jbCadastar.setText("Salvar");
        jbCadastar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastarActionPerformed(evt);
            }
        });

        jbRemover.setText("Remover");
        jbRemover.setEnabled(false);
        jbRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jbRemover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbCadastar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastar)
                    .addComponent(jbRemover)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfDiaNascimentoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tfDiaNascimentoStateChanged
        validarDataNascimento(evt);
    }//GEN-LAST:event_tfDiaNascimentoStateChanged

    private void tfMesNascimentojpDiaAdmissaoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tfMesNascimentojpDiaAdmissaoStateChanged
        validarDataNascimento(evt);
    }//GEN-LAST:event_tfMesNascimentojpDiaAdmissaoStateChanged

    private void tfAnoNascimentojpDiaAdmissaoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tfAnoNascimentojpDiaAdmissaoStateChanged
        validarDataNascimento(evt);
    }//GEN-LAST:event_tfAnoNascimentojpDiaAdmissaoStateChanged

    private void tfTelefone2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTelefone2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTelefone2ActionPerformed

    private void jpDiaAdmissaoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jpDiaAdmissaoStateChanged
        validarDataAdmissao(evt);
    }//GEN-LAST:event_jpDiaAdmissaoStateChanged

    private void jpMesAdmissaojpDiaAdmissaoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jpMesAdmissaojpDiaAdmissaoStateChanged
        validarDataAdmissao(evt);
    }//GEN-LAST:event_jpMesAdmissaojpDiaAdmissaoStateChanged

    private void jpAnoAdmissaojpDiaAdmissaoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jpAnoAdmissaojpDiaAdmissaoStateChanged
        validarDataAdmissao(evt);
    }//GEN-LAST:event_jpAnoAdmissaojpDiaAdmissaoStateChanged

    private void jbCadastarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastarActionPerformed
        try {
                if (this.rbFuncionario.isSelected()) {
                    this.cadastrarFuncionario();
                } else if (this.rbPJuridica.isSelected() || this.rbPFisica.isSelected()) {
                    this.cadastrarLocatario();
                } else {
                    this.cadastrarConcessionaria();
                }
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString(), "Erro ao cadastrar funcionário", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbCadastarActionPerformed

    private void jbRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRemoverActionPerformed
       try{
            if(this.locatarioEdicao != null){
                Persistencia.remover(this.locatarioEdicao);
                this.dispose();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString(), "Erro ao remover cliente", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbRemoverActionPerformed

    public void cadastrarConcessionaria() throws UFInvalidaException, ParseException, Exception{
        TipoLocatario tipoLocatario = TipoLocatario.CONCESSIONARIA;

        String nome = tfNome.getText();
        String nomeResponsavel = this.tfNomeResponsavel.getText();
        String razaoSocial = this.tfRazaoSocial.getText();
        String cpf = this.tfCPF.getText();
        String cnpj = this.tfCNPJ.getText();
        String ie = this.tfIE.getText();

        String data = this.tfDiaNascimento.getValue().toString() + "/" + this.tfMesNascimento.getValue().toString() + "/" + this.tfAnoNascimento.getValue().toString();
        DateFormat format = new SimpleDateFormat("dd/MM/yyyy", Locale.ENGLISH);
        Date dataNascimento = format.parse(data);

        String rua = this.tfRua.getText();
        String cep = tfCEP.getText();
        String bairro = tfBairro.getText();
        String cidade = tfCidade.getText();
        String uf = tfUF.getText();
        validarUF(uf);
        int numero = Integer.parseInt(tfNumero.getText());

        //dados de contato
        String telefonePrincipal = this.tfTelefonePrincipal.getText();
        String telefone2 = this.tfTelefone2.getText();
        String emailPrincipal = this.tfEmailPrincipal.getText();
        String email2 = this.tfEmail2.getText();

        Concessionaria concessionaria = new Concessionaria();
        concessionaria.setNome(nome);
        concessionaria.setNomeResponsavel(nomeResponsavel);
        concessionaria.setRazaoSocial(razaoSocial);
        concessionaria.setCpf(cpf);
        concessionaria.setCnpj(cnpj);
        concessionaria.setInscricaoEstadual(ie);
        concessionaria.setDataNascimento(dataNascimento);
        concessionaria.setRua(rua);
        concessionaria.setCep(cep);
        concessionaria.setBairro(bairro);
        concessionaria.setCidade(cidade);
        concessionaria.setUf(uf);
        concessionaria.setNumero(numero);

        concessionaria.setTelefonePrincipal(telefonePrincipal);
        concessionaria.setTelefone2(telefone2);
        concessionaria.setEmailPrincipal(emailPrincipal);
        concessionaria.setEmail2(email2);

        concessionaria.setTipo(tipoLocatario);

        if (this.locatarioEdicao != null) {
            concessionaria.setId(this.locatarioEdicao.getId());
            if (Main.getFuncionario() != null) {

                Main.getFuncionario().alterarCliente(concessionaria);
            } else {
                Persistencia.atualizar(concessionaria);
            }
        } else {
            if (Main.getFuncionario() != null) {
                Main.getFuncionario().cadastrarLocatario(concessionaria);
            } else {
                Persistencia.salvar(concessionaria);
            }
        }
    }
    
    private void cadastrarFuncionario() throws UFInvalidaException, ParseException, Exception{

        TipoLocatario tipoLocatario = TipoLocatario.FUNCIONARIO;

        String nome = tfNome.getText();
        String razaoSocial = this.tfRazaoSocial.getText();
        String cpf = this.tfCPF.getText();
        String cnpj = this.tfCNPJ.getText();
        String ie = this.tfIE.getText();

        String data = this.tfDiaNascimento.getValue().toString() + "/" + this.tfMesNascimento.getValue().toString() + "/" + this.tfAnoNascimento.getValue().toString();
        DateFormat format = new SimpleDateFormat("dd/MM/yyyy", Locale.ENGLISH);
        Date dataNascimento = format.parse(data);

        String rua = this.tfRua.getText();
        String cep = tfCEP.getText();
        String bairro = tfBairro.getText();
        String cidade = tfCidade.getText();
        String uf = tfUF.getText();
        validarUF(uf);
        int numero = Integer.parseInt(tfNumero.getText());

        //dados de contato
        String telefonePrincipal = this.tfTelefonePrincipal.getText();
        String telefone2 = this.tfTelefone2.getText();
        String emailPrincipal = this.tfEmailPrincipal.getText();
        String email2 = this.tfEmail2.getText();

        Funcionario funcionario = new Funcionario();
        funcionario.setNome(nome);
        funcionario.setRazaoSocial(razaoSocial);
        funcionario.setCpf(cpf);
        funcionario.setCnpj(cnpj);
        funcionario.setInscricaoEstadual(ie);
        funcionario.setDataNascimento(dataNascimento);
        funcionario.setRua(rua);
        funcionario.setCep(cep);
        funcionario.setBairro(bairro);
        funcionario.setCidade(cidade);
        funcionario.setUf(uf);
        funcionario.setNumero(numero);

        funcionario.setTelefonePrincipal(telefonePrincipal);
        funcionario.setTelefone2(telefone2);
        funcionario.setEmailPrincipal(emailPrincipal);
        funcionario.setEmail2(email2);

        funcionario.setTipo(tipoLocatario);

        //dados funcionais
        String nis = this.tfNIS.getText();
        String dataAdm = this.jpDiaAdmissao.getValue().toString() + "/" + this.jpMesAdmissao.getValue().toString() + "/" + this.jpAnoAdmissao.getValue().toString();
        Date dataAdmissao = format.parse(dataAdm);
        float salario = Float.parseFloat(this.tfSalario.getText());

        funcionario.setNis(nis);
        funcionario.setDataAdmissao(dataAdmissao);
        funcionario.setSalario(salario);

        if (this.locatarioEdicao != null) {
            funcionario.setId(this.locatarioEdicao.getId());
            if (Main.getFuncionario() != null) {

                Main.getFuncionario().alterarCliente(funcionario);
            } else {
                Persistencia.atualizar(funcionario);
            }
        } else {
            if (Main.getFuncionario() != null) {
                Main.getFuncionario().cadastrarLocatario(funcionario);
            } else {
                Persistencia.salvar(funcionario);
            }
        }

        if (this.isLogarFuncionarioAoCadastrar()) {
            Main.setFuncionario(funcionario);
        }

    }
    
    private void cadastrarLocatario() throws ParseException, UFInvalidaException, Exception {

        TipoLocatario tipoLocatario;

        if (this.rbPJuridica.isSelected()) {
            tipoLocatario = TipoLocatario.JURIDICA;
        } else {
            tipoLocatario = TipoLocatario.FISICA;
        }

        String nome = tfNome.getText();
        String razaoSocial = this.tfRazaoSocial.getText();
        String cpf = this.tfCPF.getText();
        String cnpj = this.tfCNPJ.getText();
        String ie = this.tfIE.getText();

        String data = this.tfDiaNascimento.getValue().toString() + "/" + this.tfMesNascimento.getValue().toString() + "/" + this.tfAnoNascimento.getValue().toString();
        DateFormat format = new SimpleDateFormat("dd/MM/yyyy", Locale.ENGLISH);
        Date dataNascimento = format.parse(data);

        String rua = this.tfRua.getText();
        String cep = tfCEP.getText();
        String bairro = tfBairro.getText();
        String cidade = tfCidade.getText();
        String uf = tfUF.getText();
        validarUF(uf);
        int numero = Integer.parseInt(tfNumero.getText());

        //dados de contato
        String telefonePrincipal = this.tfTelefonePrincipal.getText();
        String telefone2 = this.tfTelefone2.getText();
        String emailPrincipal = this.tfEmailPrincipal.getText();
        String email2 = this.tfEmail2.getText();

        Locatario locatario = new Locatario();
        locatario.setNome(nome);
        locatario.setRazaoSocial(razaoSocial);
        locatario.setCpf(cpf);
        locatario.setCnpj(cnpj);
        locatario.setInscricaoEstadual(ie);
        locatario.setDataNascimento(dataNascimento);
        locatario.setRua(rua);
        locatario.setCep(cep);
        locatario.setBairro(bairro);
        locatario.setCidade(cidade);
        locatario.setUf(uf);
        locatario.setNumero(numero);

        locatario.setTelefonePrincipal(telefonePrincipal);
        locatario.setTelefone2(telefone2);
        locatario.setEmailPrincipal(emailPrincipal);
        locatario.setEmail2(email2);

        locatario.setTipo(tipoLocatario);

        if (this.locatarioEdicao != null) {
            locatario.setId(this.locatarioEdicao.getId());
            if (Main.getFuncionario() != null) {

                Main.getFuncionario().alterarCliente(locatario);
            } else {
                Persistencia.atualizar(locatario);
            }
        } else {
            if (Main.getFuncionario() != null) {
                Main.getFuncionario().cadastrarLocatario(locatario);
            } else {
                Persistencia.salvar(locatario);
            }
        }

    }
    
    private void validarUF(String uf) throws UFInvalidaException {
        try
        {
            UF.valueOf(uf.toUpperCase());
        }
        catch(Exception ex)
        {
            throw new Excecoes.UFInvalidaException("A UF '"+uf+"' declarada não é válida.",ex);
        }
    }
    
    private void validarDataAdmissao(javax.swing.event.ChangeEvent evt){
        if(evt.getSource() == this.tfDiaNascimento){
            int valor = (int) this.tfDiaNascimento.getValue();
            this.tfDiaNascimento.setValue(valor<1?1:valor>31?31:valor);
        }
        else
        if(evt.getSource() == this.tfMesNascimento){
            int valor = (int) this.tfMesNascimento.getValue();
            this.tfMesNascimento.setValue(valor<1?1:valor>12?12:valor);
        }
        else
        if(evt.getSource() == this.tfAnoNascimento){
            int valor = (int) this.tfAnoNascimento.getValue();
            this.tfAnoNascimento.setValue(valor<1900?1900:valor>2500?2500:valor);
        }
    }
    private void validarDataNascimento(javax.swing.event.ChangeEvent evt){
        if(evt.getSource() == this.tfDiaNascimento){
            int valor = (int) this.tfDiaNascimento.getValue();
            this.tfDiaNascimento.setValue(valor<1?1:valor>31?31:valor);
        }
        else
        if(evt.getSource() == this.tfMesNascimento){
            int valor = (int) this.tfMesNascimento.getValue();
            this.tfMesNascimento.setValue(valor<1?1:valor>12?12:valor);
        }
        else
        if(evt.getSource() == this.tfAnoNascimento){
            int valor = (int) this.tfAnoNascimento.getValue();
            this.tfAnoNascimento.setValue(valor<1900?1900:valor>2500?2500:valor);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCadastroCliente dialog = new TelaCadastroCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbCadastar;
    private javax.swing.JButton jbRemover;
    private javax.swing.JSpinner jpAnoAdmissao;
    private javax.swing.JSpinner jpDiaAdmissao;
    private javax.swing.JSpinner jpMesAdmissao;
    private javax.swing.JRadioButton rbConcessionaria;
    private javax.swing.JRadioButton rbFuncionario;
    private javax.swing.JRadioButton rbPFisica;
    private javax.swing.JRadioButton rbPJuridica;
    private javax.swing.JSpinner tfAnoNascimento;
    private javax.swing.JTextField tfBairro;
    private javax.swing.JTextField tfCEP;
    private javax.swing.JTextField tfCNPJ;
    private javax.swing.JTextField tfCPF;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JSpinner tfDiaNascimento;
    private javax.swing.JTextField tfEmail2;
    private javax.swing.JTextField tfEmailPrincipal;
    private javax.swing.JTextField tfIE;
    private javax.swing.JTextField tfId;
    private javax.swing.JSpinner tfMesNascimento;
    private javax.swing.JTextField tfNIS;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfNomeResponsavel;
    private javax.swing.JTextField tfNumero;
    private javax.swing.JTextField tfRazaoSocial;
    private javax.swing.JTextField tfRua;
    private javax.swing.JTextField tfSalario;
    private javax.swing.JTextField tfTelefone2;
    private javax.swing.JTextField tfTelefonePrincipal;
    private javax.swing.JTextField tfUF;
    // End of variables declaration//GEN-END:variables

    private void carregarDadosLocatario() {
            if(this.locatarioEdicao.getTipo() == TipoLocatario.FISICA){
                this.rbPFisica.setSelected(true);
            }
            else if(this.locatarioEdicao.getTipo() == TipoLocatario.JURIDICA){
                this.rbPJuridica.setSelected(true);
            }
            this.jTabbedPane1.setEnabledAt(2, false);
            this.jTabbedPane1.setEnabledAt(3, false);
            
            this.tfId.setText(String.valueOf(this.locatarioEdicao.getId()));
            tfNome.setText(this.locatarioEdicao.getNome());
            this.tfRazaoSocial.setText(this.locatarioEdicao.getRazaoSocial());
            this.tfCPF.setText(this.locatarioEdicao.getCpf());
            this.tfCNPJ.setText(this.locatarioEdicao.getCnpj());
            this.tfIE.setText(this.locatarioEdicao.getInscricaoEstadual());
            
            Date dataNascimento = this.locatarioEdicao.getDataNascimento(); 
            Calendar cal = Calendar.getInstance();
            if(dataNascimento!=null){
                cal.setTime(dataNascimento);
                int diaNasc = cal.get(Calendar.YEAR);
                int mesNasc = cal.get(Calendar.MONTH);
                int anoNasc = cal.get(Calendar.DAY_OF_MONTH);

                this.tfDiaNascimento.setValue(diaNasc);
                this.tfMesNascimento.setValue(mesNasc);
                this.tfAnoNascimento.setValue(anoNasc);
            }
            this.tfRua.setText(this.locatarioEdicao.getRua());
            tfCEP.setText(this.locatarioEdicao.getCep());
            tfBairro.setText(this.locatarioEdicao.getBairro());
            tfCidade.setText(this.locatarioEdicao.getCidade());
            tfUF.setText(this.locatarioEdicao.getUf());
            
            tfNumero.setText(String.valueOf(this.locatarioEdicao.getNumero()));
            
            //dados de contato
            this.tfTelefonePrincipal.setText(this.locatarioEdicao.getTelefonePrincipal());
            this.tfTelefone2.setText(this.locatarioEdicao.getTelefone2());
            
            this.tfEmailPrincipal.setText(this.locatarioEdicao.getEmailPrincipal());
            this.tfEmail2.setText(this.locatarioEdicao.getEmail2());
    }

    private void carregarDadosFuncionario() {

        this.rbFuncionario.setSelected(true);
        this.jTabbedPane1.setEnabledAt(3, false);
        
        Funcionario funcionario = (Funcionario) this.locatarioEdicao;
        this.tfId.setText(String.valueOf(funcionario.getId()));
        tfNome.setText(funcionario.getNome());
        this.tfRazaoSocial.setText(funcionario.getRazaoSocial());
        this.tfCPF.setText(funcionario.getCpf());
        this.tfCNPJ.setText(funcionario.getCnpj());
        this.tfIE.setText(funcionario.getInscricaoEstadual());

        Calendar cal = Calendar.getInstance();

        Date dataNascimento = funcionario.getDataNascimento();
        if (dataNascimento != null) {

            cal.setTime(dataNascimento);
            int diaNasc = cal.get(Calendar.YEAR);
            int mesNasc = cal.get(Calendar.MONTH);
            int anoNasc = cal.get(Calendar.DAY_OF_MONTH);

            this.tfDiaNascimento.setValue(diaNasc);
            this.tfMesNascimento.setValue(mesNasc);
            this.tfAnoNascimento.setValue(anoNasc);
        }
        this.tfRua.setText(funcionario.getRua());
        tfCEP.setText(funcionario.getCep());
        tfBairro.setText(funcionario.getBairro());
        tfCidade.setText(funcionario.getCidade());
        tfUF.setText(funcionario.getUf());

        tfNumero.setText(String.valueOf(funcionario.getNumero()));

        //dados de contato
        this.tfTelefonePrincipal.setText(funcionario.getTelefonePrincipal());
        this.tfTelefone2.setText(funcionario.getTelefone2());

        this.tfEmailPrincipal.setText(funcionario.getEmailPrincipal());
        this.tfEmail2.setText(funcionario.getEmail2());

        this.tfNIS.setText(funcionario.getNis());

        Date dataAdmissao = funcionario.getDataAdmissao();
        if (dataAdmissao != null) {
            cal.setTime(dataAdmissao);
            int diaAdmissao = cal.get(Calendar.YEAR);
            int mesAdmissao = cal.get(Calendar.MONTH);
            int anoAdmissao = cal.get(Calendar.DAY_OF_MONTH);
            this.jpDiaAdmissao.setValue(diaAdmissao);
            this.jpMesAdmissao.setValue(mesAdmissao);
            this.jpAnoAdmissao.setValue(anoAdmissao);
        }
        this.tfSalario.setText(String.valueOf(funcionario.getSalario()));

    }

    private void carregarDadosConcessionaria() {
            
            this.rbConcessionaria.setSelected(true);
            Concessionaria concessionaria = (Concessionaria)this.locatarioEdicao;
            this.tfId.setText(String.valueOf(concessionaria.getId()));
            tfNome.setText(concessionaria.getNome());
            this.tfRazaoSocial.setText(concessionaria.getRazaoSocial());
            this.tfCPF.setText(concessionaria.getCpf());
            this.tfCNPJ.setText(concessionaria.getCnpj());
            this.tfIE.setText(concessionaria.getInscricaoEstadual());
            
            Date dataNascimento = concessionaria.getDataNascimento(); 
            Calendar cal = Calendar.getInstance();
            if (dataNascimento != null) {
                cal.setTime(dataNascimento);
                int diaNasc = cal.get(Calendar.YEAR);
                int mesNasc = cal.get(Calendar.MONTH);
                int anoNasc = cal.get(Calendar.DAY_OF_MONTH);

                this.tfDiaNascimento.setValue(diaNasc);
                this.tfMesNascimento.setValue(mesNasc);
                this.tfAnoNascimento.setValue(anoNasc);
            }
            this.tfRua.setText(concessionaria.getRua());
            tfCEP.setText(concessionaria.getCep());
            tfBairro.setText(concessionaria.getBairro());
            tfCidade.setText(concessionaria.getCidade());
            tfUF.setText(concessionaria.getUf());
            
            tfNumero.setText(String.valueOf(concessionaria.getNumero()));
            
            //dados de contato
            this.tfTelefonePrincipal.setText(concessionaria.getTelefonePrincipal());
            this.tfTelefone2.setText(concessionaria.getTelefone2());
            
            this.tfEmailPrincipal.setText(concessionaria.getEmailPrincipal());
            this.tfEmail2.setText(concessionaria.getEmail2());
            
            this.tfNomeResponsavel.setText(concessionaria.getNomeResponsavel());
            
    }
}
