/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.Concessionaria;
import Classes.Equipamento;
import Classes.Historico;
import Classes.ImageUtils;
import Classes.StatusEquipamento;
import Classes.TipoOcorrencia;
import Database.Persistencia;
import java.awt.Frame;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.xml.bind.DatatypeConverter;

/**
 *
 * @author Vitor
 */
public class TelaCadastroEquipamento extends javax.swing.JDialog {

    /**
     * Creates new form TelaCadastroEquipamentoJD
     *
     * @param parent
     * @param modal
     */
    private Equipamento equipamentoEdicao;
    BufferedImage img = null;
    //Create a file chooser
    final JFileChooser fc = new JFileChooser();

    public TelaCadastroEquipamento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    TelaCadastroEquipamento(TelaVisualizarEquipamentos parent, boolean modal, Equipamento equipamento) {
        super(parent, modal);
        initComponents();
        this.equipamentoEdicao = equipamento;
        this.jbRemover.setEnabled(true);
        jpReplicas.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jbRemover = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jtfEAN = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtfCategoria = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfFabricante = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtfId = new javax.swing.JTextField();
        jtfStatus = new javax.swing.JTextField();
        jtfValorDiaria = new javax.swing.JTextField();
        jtfValorPatrimonio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfConcessionaria = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jtfNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDescricao = new javax.swing.JTextArea();
        jspValidade = new javax.swing.JSpinner();
        jspDataProxRevisao = new javax.swing.JSpinner();
        jspDataCompra = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        jlImagem = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jpReplicas = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Equipamento");
        setResizable(false);

        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jbRemover.setText("Remover");
        jbRemover.setEnabled(false);
        jbRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRemoverActionPerformed(evt);
            }
        });

        jtfEAN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfEANFocusLost(evt);
            }
        });

        jLabel1.setText("Id:");

        jtfCategoria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCategoriaFocusLost(evt);
            }
        });

        jLabel2.setText("Nome:");

        jtfFabricante.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfFabricanteFocusLost(evt);
            }
        });

        jLabel3.setText("Série:");

        jLabel8.setText("Data da Compra:");

        jLabel9.setText("Próxima Revisão:");

        jLabel10.setText("Validade:");

        jLabel11.setText("Valor Diária (R$):");

        jLabel12.setText("Valor do Patrimônio (R$):");

        jLabel13.setText("Status:");

        jtfId.setEditable(false);

        jtfStatus.setEditable(false);

        jtfValorDiaria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfValorDiariaFocusLost(evt);
            }
        });

        jtfValorPatrimonio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfValorPatrimonioFocusLost(evt);
            }
        });

        jLabel4.setText("Concessionária:");

        jLabel5.setText("Descrição:");

        jtfConcessionaria.setEditable(false);

        jLabel6.setText("Categoria:");

        jLabel7.setText("Fabricante:");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jtfNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfNomeFocusLost(evt);
            }
        });

        jtaDescricao.setColumns(20);
        jtaDescricao.setLineWrap(true);
        jtaDescricao.setRows(5);
        jtaDescricao.setWrapStyleWord(true);
        jtaDescricao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtaDescricaoFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(jtaDescricao);

        jspValidade.setModel(new javax.swing.SpinnerDateModel());
        JSpinner.DateEditor d = new JSpinner.DateEditor(jspValidade, "dd/MM/yyyy");
        jspValidade.setEditor(d);
        jspValidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jspValidadeFocusLost(evt);
            }
        });

        jspDataProxRevisao.setModel(new javax.swing.SpinnerDateModel());
        JSpinner.DateEditor jspDataProxRevisaoD = new JSpinner.DateEditor(jspDataProxRevisao, "dd/MM/yyyy");
        jspDataProxRevisao.setEditor(jspDataProxRevisaoD);
        jspDataProxRevisao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jspDataProxRevisaoFocusLost(evt);
            }
        });

        jspDataCompra.setModel(new javax.swing.SpinnerDateModel());
        JSpinner.DateEditor jspDataCompraD = new JSpinner.DateEditor(jspDataCompra, "dd/MM/yyyy");
        jspDataCompra.setEditor(jspDataCompraD);
        jspDataCompra.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jspDataCompraStateChanged(evt);
            }
        });

        jLabel16.setText("Imagem:");

        jlImagem.setBackground(new java.awt.Color(235, 210, 210));
        jlImagem.setAutoscrolls(true);
        jlImagem.setMaximumSize(new java.awt.Dimension(267, 122));
        jlImagem.setMinimumSize(new java.awt.Dimension(267, 122));

        jButton3.setText("Escolher");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jtfNome)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(78, 78, 78)
                                        .addComponent(jLabel3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jtfStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtfEAN, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(90, 92, Short.MAX_VALUE))
                            .addComponent(jspValidade)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfValorDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel11))
                            .addComponent(jLabel12)
                            .addComponent(jtfValorPatrimonio, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jspDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jtfFabricante)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jspDataProxRevisao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jtfConcessionaria, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1)))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel13)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfEAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jspValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jspDataProxRevisao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jspDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfConcessionaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfValorDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))
                        .addGap(7, 7, 7)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfValorPatrimonio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 32, Short.MAX_VALUE))
                    .addComponent(jlImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Dados Cadastrais", jPanel1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Descrição", "Tipo", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(75);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(75);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Histórico", jPanel2);

        jLabel14.setText("Replicar:");

        jpReplicas.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 1));

        jLabel15.setText("X o cadastro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jbRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpReplicas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jpReplicas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbRemover)
                        .addComponent(jButton2))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DialogoBuscarConcessionaria dialogo = new DialogoBuscarConcessionaria((Frame) null, true);
        dialogo.setVisible(true);
        Concessionaria conc = dialogo.getConcessionariaSelecionada();
        if (conc != null) {
            jtfConcessionaria.setText(String.valueOf(conc.getNome()));
            if (equipamentoEdicao == null) {
                equipamentoEdicao = new Equipamento();
            }
            try {
                equipamentoEdicao.setConcessionaria(conc);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.toString(), "Validação", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (equipamentoEdicao == null) {
            return;
        }
        try {

            Set<Historico> historicos = equipamentoEdicao.getHistoricos();

            if (historicos == null) {
                historicos = new HashSet<>();
                equipamentoEdicao.setHistoricos(historicos);
            }
            Historico historico = new Historico();
            historico.setDataOcorrencia(new Date());

            if (equipamentoEdicao.getId() == 0) {
                equipamentoEdicao.setStatus(StatusEquipamento.Disponivel);
                historico.setDescricao("Cadastro realizado por " + (Main.getFuncionario() == null ? " desconhecido" : Main.getFuncionario().getNome()));
                historico.setTipoOcorrencia(TipoOcorrencia.Cadastro);
                equipamentoEdicao.getHistoricos().add(historico);

                int replicas = (int) jpReplicas.getValue() + 1;

                for (int i = 0; i < replicas; i++) {

                    if (i > 0) {
                        equipamentoEdicao = equipamentoEdicao.clone();
                    }
                    if (Main.getFuncionario() == null) {
                        Persistencia.salvar(equipamentoEdicao);
                    } else {
                        Main.getFuncionario().cadastrarEquipamento(equipamentoEdicao);
                    }
                }
            } else {
                historico.setDescricao("Alteracao de Cadastro realizada por " + (Main.getFuncionario() == null ? " desconhecido" : Main.getFuncionario().getNome()));
                historico.setTipoOcorrencia(TipoOcorrencia.AlteracaoCadastro);
                equipamentoEdicao.getHistoricos().add(historico);

                if (Main.getFuncionario() == null) {
                    Persistencia.atualizar(equipamentoEdicao);
                } else {
                    Main.getFuncionario().atualizarEquipamento(equipamentoEdicao);
                }
            }
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString(), "Salvar Equipamento", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtaDescricaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtaDescricaoFocusLost
        if (equipamentoEdicao == null) {
            equipamentoEdicao = new Equipamento();
        }
        try {
            equipamentoEdicao.setDescricao(this.jtaDescricao.getText());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString(), "Validação", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtaDescricaoFocusLost

    private void jtfEANFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfEANFocusLost
        if (equipamentoEdicao == null) {
            equipamentoEdicao = new Equipamento();
        }
        try {
            equipamentoEdicao.setSerie(jtfEAN.getText());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString(), "Validação", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtfEANFocusLost

    private void jtfNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNomeFocusLost
        if (equipamentoEdicao == null) {
            equipamentoEdicao = new Equipamento();
        }
        try {
            equipamentoEdicao.setNome(jtfNome.getText());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString(), "Validação", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtfNomeFocusLost

    private void jtfCategoriaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCategoriaFocusLost
        if (equipamentoEdicao == null) {
            equipamentoEdicao = new Equipamento();
        }
        try {
            equipamentoEdicao.setCategoria(this.jtfCategoria.getText());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString(), "Validação", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtfCategoriaFocusLost

    private void jtfFabricanteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfFabricanteFocusLost
        if (equipamentoEdicao == null) {
            equipamentoEdicao = new Equipamento();
        }
        try {
            equipamentoEdicao.setFabricante(this.jtfFabricante.getText());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString(), "Validação", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtfFabricanteFocusLost

    private void jtfValorDiariaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfValorDiariaFocusLost
        if (equipamentoEdicao == null) {
            equipamentoEdicao = new Equipamento();
        }
        try {
            equipamentoEdicao.setValorDiaria(Float.parseFloat(jtfValorDiaria.getText()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString(), "Validação", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtfValorDiariaFocusLost

    private void jtfValorPatrimonioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfValorPatrimonioFocusLost
        if (equipamentoEdicao == null) {
            equipamentoEdicao = new Equipamento();
        }
        try {
            equipamentoEdicao.setValorPatrimonio(Float.parseFloat(jtfValorPatrimonio.getText()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString(), "Validação", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtfValorPatrimonioFocusLost

    private void jspValidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jspValidadeFocusLost
        if (equipamentoEdicao == null) {
            equipamentoEdicao = new Equipamento();
        }
        try {
            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            Date data = new Date(format.parse(jspValidade.getValue().toString()).getTime());
            equipamentoEdicao.setValidade(data);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString(), "Validação", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jspValidadeFocusLost

    private void jspDataProxRevisaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jspDataProxRevisaoFocusLost
        if (equipamentoEdicao == null) {
            equipamentoEdicao = new Equipamento();
        }
        try {
            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            Date data = new Date(format.parse(jspDataProxRevisao.getValue().toString()).getTime());
            equipamentoEdicao.setProximaRevisao(data);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString(), "Validação", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jspDataProxRevisaoFocusLost

    private void jspDataCompraStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jspDataCompraStateChanged
        if (equipamentoEdicao == null) {
            equipamentoEdicao = new Equipamento();
        }
        try {
            equipamentoEdicao.setDataCompra((Date) jspDataCompra.getValue());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString(), "Validação", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jspDataCompraStateChanged

    private void jbRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRemoverActionPerformed
        try {
            if (this.equipamentoEdicao != null) {
                this.equipamentoEdicao.setStatus(StatusEquipamento.Apagado);
                if (Main.getFuncionario() != null) {

                    Main.getFuncionario().atualizarEquipamento(equipamentoEdicao);
                } else {
                    Persistencia.atualizar(equipamentoEdicao);
                }
                this.dispose();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString(), "Erro ao remover equipamento", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbRemoverActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        FileFilter filter = new FileNameExtensionFilter("JPG File", "jpg");
        fc.setFileFilter(filter);
        int returnVal = fc.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();

            try {
                String path = file.getAbsolutePath();
                img = ImageIO.read(new File(path));

                ImageIcon imageIcon = new ImageIcon(ImageUtils.resize(img, 267, 122));
                jlImagem.setIcon(imageIcon);
                ByteArrayOutputStream output = new ByteArrayOutputStream();
                ImageIO.write(img, "jpg", output);
                String printBase64Binary = DatatypeConverter.printBase64Binary(output.toByteArray());

                if (equipamentoEdicao == null) {
                    equipamentoEdicao = new Equipamento();
                }
                try {
                    equipamentoEdicao.setImagemBase64(printBase64Binary);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.toString(), "Validação", JOptionPane.ERROR_MESSAGE);
                }

            } catch (IOException ex) {

                JOptionPane.showMessageDialog(null, ex.toString(), "Erro abrir imagem", JOptionPane.ERROR_MESSAGE);

            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCadastroEquipamento dialog = new TelaCadastroEquipamento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbRemover;
    private javax.swing.JLabel jlImagem;
    private javax.swing.JSpinner jpReplicas;
    private javax.swing.JSpinner jspDataCompra;
    private javax.swing.JSpinner jspDataProxRevisao;
    private javax.swing.JSpinner jspValidade;
    private javax.swing.JTextArea jtaDescricao;
    private javax.swing.JTextField jtfCategoria;
    private javax.swing.JTextField jtfConcessionaria;
    private javax.swing.JTextField jtfEAN;
    private javax.swing.JTextField jtfFabricante;
    private javax.swing.JTextField jtfId;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfStatus;
    private javax.swing.JTextField jtfValorDiaria;
    private javax.swing.JTextField jtfValorPatrimonio;
    // End of variables declaration//GEN-END:variables

    public void carregarDadosEquipamentoEdicao() {

        jtfId.setText(String.valueOf(equipamentoEdicao.getId()));
        jtfStatus.setText(equipamentoEdicao.getStatus().name());
        jtfEAN.setText(equipamentoEdicao.getSerie());
        
        jspValidade.setValue(equipamentoEdicao.getValidade());
        jtfNome.setText(equipamentoEdicao.getNome());
        jtaDescricao.setText(equipamentoEdicao.getDescricao());
        jtfCategoria.setText(equipamentoEdicao.getCategoria());
        jtfFabricante.setText(equipamentoEdicao.getFabricante());

        jspDataCompra.setValue(equipamentoEdicao.getDataCompra());

        jspDataProxRevisao.setValue(equipamentoEdicao.getProximaRevisao());
        if (equipamentoEdicao.getConcessionaria() != null) {
            jtfConcessionaria.setText(equipamentoEdicao.getConcessionaria().getNome());
        } else {
            jtfConcessionaria.setText("N/A");
        }
        jtfValorDiaria.setText(String.valueOf(equipamentoEdicao.getValorDiaria()));
        jtfValorPatrimonio.setText(String.valueOf(equipamentoEdicao.getValorPatrimonio()));

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        try {
            Set<Historico> historicos = equipamentoEdicao.getHistoricos();
            SimpleDateFormat out = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
            for (Historico historico : historicos) {
                Object[] linha = new Object[]{
                    historico,
                    historico.getDescricao(),
                    historico.getTipoOcorrencia(),
                    out.format(historico.getDataOcorrencia())
                };
                model.addRow(linha);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString(), "Erro ao obter clientes", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
            try {
                BufferedImage bImageFromConvert = equipamentoEdicao.obterImagem();
                ImageIcon imageIcon = new ImageIcon(ImageUtils.resize(bImageFromConvert, 267, 122));
                jlImagem.setIcon(imageIcon);

            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, ex.toString(), "Erro ao carregar imagem do equipamento", JOptionPane.ERROR_MESSAGE);

                Logger.getLogger(TelaCadastroEquipamento.class.getName()).log(Level.SEVERE, null, ex);
            }
            catch(Exception ex){}
        
    }
}
